version: 2
jobs:
  build:
    working_directory: /tmp/docker-digdag

    docker:
      - image: circleci/ruby:2.5.1

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Check docker version
          command: |
            set -x
            docker version
            docker info

      - run:
          name: Build digdag image
          command: |
            set -x
            docker build -t minimum2scp/digdag:ci .

      - run: bundle check || bundle install --jobs=4

      - run: DOCKER_IMAGE=minimum2scp/digdag:ci bundle exec rspec spec/digdag/

