# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
    version_requirement_updates: "auto"
    default_reviewers:
      - "minimum2scp"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "minimum2scp"

